# Generated by Django 4.2.30 on 2026-04-28 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=500)),
                ('current_lat', models.FloatField()),
                ('current_lng', models.FloatField()),
                ('pickup_location', models.CharField(max_length=500)),
                ('pickup_lat', models.FloatField()),
                ('pickup_lng', models.FloatField()),
                ('dropoff_location', models.CharField(max_length=500)),
                ('dropoff_lat', models.FloatField()),
                ('dropoff_lng', models.FloatField()),
                ('current_cycle_used', models.FloatField(help_text='Hours already used in current 70-hr cycle')),
                ('total_distance_miles', models.FloatField(blank=True, null=True)),
                ('total_drive_hours', models.FloatField(blank=True, null=True)),
                ('total_days', models.IntegerField(blank=True, null=True)),
                ('total_rest_stops', models.IntegerField(blank=True, null=True)),
                ('total_fuel_stops', models.IntegerField(blank=True, null=True)),
                ('route_geometry', models.TextField(blank=True, help_text='JSON list of [lng, lat] pairs', null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('error', 'Error'), ('pdf_downloaded', 'PDF Downloaded')], default='planned', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_type', models.CharField(choices=[('DRIVING', 'Driving'), ('ON_DUTY', 'On Duty (not driving)'), ('BREAK', '30-Min Break'), ('SLEEPER', '10-Hr Sleeper Berth'), ('FUEL_STOP', 'Fuel Stop')], max_length=20)),
                ('sequence', models.IntegerField(help_text='Order of this segment in the trip')),
                ('start_time_offset', models.FloatField(help_text='Minutes from trip start when segment begins')),
                ('end_time_offset', models.FloatField(help_text='Minutes from trip start when segment ends')),
                ('duration_minutes', models.FloatField()),
                ('distance_miles', models.FloatField(default=0.0, help_text='Miles covered in this segment (0 for non-driving)')),
                ('odometer_start', models.FloatField(default=0.0)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('day_index', models.IntegerField(default=0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='trips.trip')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='ELDLogSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_index', models.IntegerField(help_text='0-indexed day number from trip start')),
                ('date_label', models.CharField(help_text="Human-readable date e.g. 'Day 1'", max_length=50)),
                ('off_duty_slots', models.TextField(default='[]')),
                ('sleeper_slots', models.TextField(default='[]')),
                ('driving_slots', models.TextField(default='[]')),
                ('on_duty_slots', models.TextField(default='[]')),
                ('total_off_duty_hours', models.FloatField(default=0.0)),
                ('total_sleeper_hours', models.FloatField(default=0.0)),
                ('total_driving_hours', models.FloatField(default=0.0)),
                ('total_on_duty_hours', models.FloatField(default=0.0)),
                ('remarks', models.TextField(blank=True, default='')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_sheets', to='trips.trip')),
            ],
            options={
                'ordering': ['day_index'],
            },
        ),
    ]
